### ISSUE TITLE
This theme broke my roundcube install - 1.3.8

### ISSUE THREAD

**Issue by Sebastiaan76** [nazrul-357/materializerc#1]
No way to get back into settings to reset, and even editing config.inc.php everything is broken. 

Definitely not a them to try, unless you want it and nothing else.

How do I get rid of this theme now and restore my roundcube install?

**Comment by nazrul-357** [comment]
Hi @Sebastiaan76 ,

Sorry to hear that it broke your install. This theme works only by including the provided skin and plugin and then enabling them in the main `config.inc.php`, just like any other skins and plugins. It never overwrites anything on the roundcube installation. Please consult `readme` for proper installation.

To disable the theme, you need access to main `config.inc.php` and remove materialize from skin and plugin.

Regards
